Released 5.8.0-rc.20

diff --git a/latest/kubectl-provision b/latest/kubectl-provision
--- a/latest/kubectl-provision
+++ b/latest/kubectl-provision
@@ -26,7 +26,7 @@ Copyright (C) 2022-2023 scontain.com
 
 set -e
 
-export K_PROVISION_VERSION="5.8.0-rc.19"
+export K_PROVISION_VERSION="5.8.0-rc.20"
 export K_SGX_TOLERATIONS="--accept-configuration-needed --accept-group-out-of-date --accept-sw-hardening-needed"
 export K_MRSIGNER_DB="195e5a6df987d6a515dd083750c1ea352283f8364d3ec9142b0d593988c6ed2d"
 export K_MRSIGNER_SCONTAIN="b6c14ae06a05284253b548038e269f8225718bc0856828f491ed85174ccc2979"
@@ -2393,7 +2393,7 @@ if [[ $EXISTS == 0 ]] ; then
     template_file="$TARGET_DIR/owner-config/cas-$NAMESPACE-$NAME-$VERSION-provisioning-step.yaml.template"
     manifest="$TARGET_DIR/owner-config/cas-$NAMESPACE-$NAME-$VERSION-provisioning-step.yaml"
 
-    verbose "Creating manifest '$manifest' for CAS provsioning"
+    verbose "Creating manifest '$manifest' for CAS provisioning"
     download_file "$CAS_PROVISIONING_URL" "$template_file"
 
     SCONE="\$SCONE" envsubst < "$template_file" > "$manifest"
@@ -2566,7 +2566,7 @@ EOF
             -e SGX_TOLERATIONS="$SGX_TOLERATIONS" \
             -e SGX_STD_TOLERATIONS="$SGX_STD_TOLERATIONS" \
             -e SCONE_NO_TIME_THREAD=1 \
-            ${SCONECLI_IMAGE} sh -c "scone cas provision host.docker.internal -c $CAS_KEY_HASH --token $CAS_PROVISIONING_TOKEN  --config-file /owner-config/config.toml  with-attestation  $SGX_TOLERATIONS ; if [ $? != 0 ] ; then echo 'Provisioning failed - checking if it is already partitioned!' ; scone session read provisioned 2> /dev/null ; if [ $? != 0 ] ; then  echo 'Provisioning of CAS failed! FATAL ERROR: please ensure that you use a CAS that permits DB-Key injection or correct SGX_TOLERATIONS to SGX_STD_TOLERATIONS' ; exit 1 ; else  echo 'CAS is already provisioned' ; fi ; fi "
+            ${SCONECLI_IMAGE} sh -c 'scone cas provision host.docker.internal -c $CAS_KEY_HASH --token $CAS_PROVISIONING_TOKEN  --config-file /owner-config/config.toml  with-attestation  $SGX_TOLERATIONS || scone cas provision host.docker.internal -c $CAS_KEY_HASH --token $CAS_PROVISIONING_TOKEN  --config-file /owner-config/config.toml  with-attestation  $SGX_STD_TOLERATIONS || { echo "Provisioning failed - checking if it is already provisioned!" ; scone session read provisioned 2> /dev/null ; if [ $? != 0 ] ; then  echo "Provisioning of CAS failed! FATAL ERROR: please ensure that you use a CAS that permits DB-Key injection or correct SGX_TOLERATIONS to SGX_STD_TOLERATIONS" ; exit 1 ; else  echo "CAS is already provisioned" ; fi } '
 
         upload_post_provisioning_sessions
     fi
diff --git a/latest/operator_controller b/latest/operator_controller
--- a/latest/operator_controller
+++ b/latest/operator_controller
@@ -42,7 +42,7 @@ this script or by providing a config file $CONFIG_FILE (default is "operator_con
 
 set -e
 
-export K_PROVISION_VERSION="5.8.0-rc.19"
+export K_PROVISION_VERSION="5.8.0-rc.20"
 export RED='\e[31m'
 export BLUE='\e[34m'
 export ORANGE='\e[33m'
@@ -70,6 +70,8 @@ trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
 trap 'if [ $? -ne 0 ]; then echo -e "${RED}\"${last_command}\" command failed - exiting.${NC}" ; fi' EXIT
 
 # CONFIG SECTION - some configuration options only be changed via environment variables (and not yet via command line flags)
+
+export DCAP_KEY=""
 
 if [[ "$CONFIG_FILE" == "" ]] ; then
     CONFIG_FILE="operator_controller_config"
@@ -533,6 +535,8 @@ print_version_flag="--version"
 only_controller_flag="--only-operator"
 no_sgxplugin="--no-sgxplugin"
 verify_sign_key_flag="--verify-image-signatures"
+dcap_flag="--dcap-api"
+dcap_short_flag="-d"
 
 NAMESPACE="$DEFAULT_NAMESPACE"
 repo="$APP_IMAGE_REPO"
@@ -619,6 +623,8 @@ usage ()
   echo "                  For the verification of signed images in the $SCONTAIN_IMAGE_REPO"
   echo "                  repository, the public key does not need to be provided, and this"
   echo "                  option is ignored."
+  echo "    $dcap_flag | $dcap_short_flag <DCAP API Key>"
+  echo "                  DCAP API Key - required when provisioning LAS."
   echo "    $help_flag"
   echo "                  Output this usage information and exit."
   echo ""
@@ -642,6 +648,15 @@ usage ()
 
 while [[ "$#" -gt 0 ]]; do
   case $1 in
+    ${dcap_flag} | ${dcap_short_flag})
+      export DCAP_KEY="$2"
+      if [ ! -n "${DCAP_KEY}" ]; then
+        usage
+        error_exit "Error: Please specify a valid DCAP_KEY ('$DCAP_KEY' is invalid)."
+      fi
+      shift # past argument
+      shift || true # past value
+      ;;
     ${ns_flag} | ${ns_short_flag})
       NAMESPACE="$2"
       if [ ! -n "${NAMESPACE}" ]; then
@@ -1028,6 +1043,9 @@ then
             verify_image "las" "$VERSION"
         else
             warning "Skipping verification of signature of las image, due to unknown origin of LAS_MANIFEST=$LAS_MANIFEST"
+        fi
+        if [[ "$DCAP_KEY" == "" ]]; then
+            warning "LAS's liveness probe will be disabled since the DCAP API key was not provided with the $dcap_flag flag."
         fi
         kubectl apply -f ".las-manifest.yaml"
     fi
